### ISSUE TITLE
build_with_cors perhaps needs updating?

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/enterprise-architectures-and-patterns#12]
Hi
Thanks for this repo. Really useful
I am compiling a Rust application that uses CORS.

I am getting the following error when using the `build_with_cors` function:

```bash
 .build_with_cors(&req, &load_cors_config()))
    |          ^^^^^^^^^^^^^^^ ----  ------------------- an argument of type `std::string::String` is missing
    |                          |
    |                          expected `&Method`, found `&Request`
```

It seems to want 3 arguments:

```bash
.build_with_cors(/* &spin_sdk::http::Method */, /* std::string::String */, &load_cors_config()))
```

Ref: https://github.com/fermyon/enterprise-architectures-and-patterns/blob/main/cors-rust/src/lib.rs#L57

**Comment by tpmccallum** [comment]
I am using `spin-contrib-http = "0.0.7"` and the example's Cargo.toml is using `spin-contrib-http = "0.0.5"` - I will downgrade for the time being.

**Comment by ThorstenHans** [comment]
@tpmccallum good catch. I've updated the sample to latest `0.0.8` (which I released earlier today).

I also updated the docs for this sample to illustrate how one could set allowed CORS origins using the Environment Variable Provider.
